Parse data from url
YuriyHrechka/School-Parser pull request #2
Opened 2024-09-01 13:56 UTC by YuriyHrechka

Added new method that is parse valid data.

2024-09-01 14:17 UTC, MaksStud requested changes

2024-09-01 14:17 UTC, MaksStud commented on services.py
> +        valid_data = ['№ у системі:', 'Скорочена:', 'Поштова адреса:', 'Телефони:', 'E-mail:', 'Директор:', 'Спроможність закладу освіти (учнів):', 'Кількість учнів:']
This list and validation system must be another file and method

2024-09-01 14:17 UTC, MaksStud commented on services.py
> +                    if th_text in valid_data:
Write another method from validation data, rename valid_data to validation_parameter_list

2024-09-01 14:17 UTC, MaksStud commented on services.py
> +                        data_dict[th_text] = td_text
Use method from add

2024-09-01 14:17 UTC, MaksStud commented on services.py
> +                if th and td:
Rename variables, this name is incorrect

2024-09-01 14:17 UTC, MaksStud commented on main.py
> +print(a.parse_data(a.base_url_list()[0]))
Write a method from the parses full school from base_url_list

2024-09-02 05:08 UTC, YuriyHrechka commented on services.py
> +from utils import valid_data
If we add new imports, we need to change requirements

2024-09-02 17:24 UTC, merged